### ISSUE TITLE
L1 

### ISSUE THREAD

**Issue by Anatoliy-Burlai** [Geekhub-J4W/geekhub-j4w-12-Tolya-7#1]
L1 Hello World!
![IMG_20221019_193753](https://user-images.githubusercontent.com/116194643/197328045-2dbbac55-a510-40c5-baa8-50c048976a11.jpg)
![IMG_20221019_195803](https://user-images.githubusercontent.com/116194643/197328048-2e0da995-e90d-49ca-a097-d7893d81ece9.jpg)
![IMG_20221019_210522](https://user-images.githubusercontent.com/116194643/197328049-34733476-600a-461a-b947-49215fac45a8.jpg)
![IMG_20221019_211608](https://user-images.githubusercontent.com/116194643/197328050-179c4f16-264b-425f-be70-50902fbaf59f.jpg)
![IMG_20221020_181017](https://user-images.githubusercontent.com/116194643/197328054-ff7e73ff-ba2d-4947-a9c9-144096ff6e0a.jpg)
![IMG_20221020_194347](https://user-images.githubusercontent.com/116194643/197328055-f004c00c-049c-492e-bf19-a3de742ad192.jpg)
![IMG_20221020_212826](https://user-images.githubusercontent.com/116194643/197328057-8ef8c700-8c60-4aac-a7f0-3e407a4301f1.jpg)
![IMG_20221021_112559](https://user-images.githubusercontent.com/116194643/197328059-2af4f181-f4fc-4ffe-bfce-a72658f3a662.jpg)
![IMG_20221021_113041](https://user-images.githubusercontent.com/116194643/197328060-9b61ec4c-f001-4e5a-97d8-f08d22810393.jpg)
![IMG_20221021_113606](https://user-images.githubusercontent.com/116194643/197328062-5075b71e-1c7c-4116-be62-dac5d2f495dd.jpg)
![IMG_20221021_122832](https://user-images.githubusercontent.com/116194643/197328063-fc014804-6155-4213-a8e6-e637ef2d34f8.jpg)
![IMG_20221021_131738](https://user-images.githubusercontent.com/116194643/197328065-83d25d53-dfb7-415e-bdd8-a50da3298903.jpg)

**Comment by V-Nikolenko** [comment]
Good job!
